version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
      working_directory: ~/circleCI_root/api
    steps:
      - checkout:
          path: ~/circleCI_root
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7-node
      - image: circleci/postgres:12.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: 127.0.0.1
      RAILS_ENV: test
      working_directory: ~/circleCI_root/api
    steps:
      - checkout:
          path: ~/circleCI_root
      - ruby/install-deps
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
